Add createTransaction.js test
InkProtocol/contracts pull request #4
Opened 2018-01-29 05:14 UTC by ilake

2018-01-30 00:26 UTC, ngan requested changes

2018-01-30 00:26 UTC, ngan commented on test/createTransaction.js
> +      assert.equal(eventArgs.value, amount)
We don't need to test XNK transfer to the buyer.

2018-01-30 00:26 UTC, ngan commented on test/createTransaction.js
> +        let policy_address = 0;
Please use camel casing.

2018-01-30 06:40 UTC, ngan requested changes

2018-01-30 06:40 UTC, ngan commented on test/createTransaction.js
> +      eventArgs = $util.eventFromTx(tx, $util.events.TransactionInitiated).args
Missing let

2018-01-30 06:40 UTC, ngan commented on test/createTransaction.js
> +      eventArgs1 = $util.eventFromTx(tx1, $util.events.TransactionInitiated).args
Missing let

2018-01-30 06:40 UTC, ngan commented on test/createTransaction.js
> +      assert.equal(eventArgs.seller, seller)
Why test for this?

2018-01-31 08:10 UTC, ilake commented
@ngan please review this, thanks

2018-01-31 19:19 UTC, merged