Add specs to confirmTransaction
InkProtocol/contracts pull request #5
Opened 2018-01-30 04:23 UTC by kraytruthg

## WIP

- Add specs to confirmTransaction

2018-01-30 07:45 UTC, kraytruthg commented
The state `ConfirmedAfterEscalation` is not handled in `_fetchMediatorFee`.
So specs for **Escalation** are pending.

2018-01-30 16:16 UTC, kraytruthg commented
@ngan 

The mediator fee for these events should always be **0**, right?
Why do we choose to record it in the event?
``` solidity
  // Event emitted when a transaction is confirmed by the buyer after the
  // mediation expiry.
  event TransactionConfirmedAfterEscalation(
    uint256 indexed id,
    uint256 mediatorFee
  );

  // Event emitted when a transaction is refunded by the seller after the
  // mediation expiry.
  event TransactionRefundedAfterEscalation(
    uint256 indexed id,
    uint256 mediatorFee
  );
```

2018-01-31 03:33 UTC, ngan requested changes

2018-01-31 03:33 UTC, ngan commented on test/confirmTransaction.js
> +        buyer, seller, { finalState: $util.states.Accepted }
Can you fix the formatting on this?

```
} = await $util.buildTransaction(buyer, seller, {
  ...
})
```

2018-01-31 03:39 UTC, ngan commented on test/confirmTransaction.js
> +        let tx = await protocol.confirmTransaction(transaction.id, { from: buyer })
Do you need reference to `tx?

2018-01-31 09:10 UTC, kraytruthg commented
@ngan this is good to review

2018-01-31 18:48 UTC, merged