Add escalateDisputeToMediator test
InkProtocol/contracts pull request #6
Opened 2018-01-30 06:13 UTC by ilake

2018-01-30 06:32 UTC, ngan requested changes

2018-01-30 06:32 UTC, ngan commented on test/escalateDisputeToMediator.js
>      protocol = await InkProtocol.new()
Is this needed?

2018-01-30 06:32 UTC, ngan commented on test/escalateDisputeToMediator.js
>      protocol = await InkProtocol.new()
If not, let’s remove this and the let statement above as well.

2018-01-30 06:32 UTC, ngan commented on test/escalateDisputeToMediator.js
> +      assert.equal(transaction.state, $util.states.Escalated)
Let’s remove line 89 and 91. The state is actually internal and the getTransaction method just assumes it’s in that state.

2018-01-31 08:07 UTC, ilake commented
@ngan please review this, thanks

2018-01-31 18:34 UTC, merged