Add disputeTransaction spec
InkProtocol/contracts pull request #7
Opened 2018-01-30 07:56 UTC by tubaxenor

2018-01-30 07:57 UTC, tubaxenor commented
@ngan, this is good to review

2018-01-30 23:52 UTC, ngan requested changes

2018-01-30 23:52 UTC, ngan commented on test/disputeTransaction.js
> +  unknown = accounts[accounts.length - 1]
Missing `let`.

2018-01-30 23:52 UTC, ngan commented on test/disputeTransaction.js
> +const ErroredPolicy = artifacts.require("./mocks/ErrorPolicyMock.sol")
`ErrorPolicy`

2018-01-30 23:52 UTC, ngan commented on test/disputeTransaction.js
> +      $util.advanceTime(fulfillmentExpiry.toNumber() - 600)
Let's go with 10 seconds.

2018-01-30 23:52 UTC, ngan commented on test/disputeTransaction.js
> +      await protocol.disputeTransaction(transaction.id, {from: buyer})
Let's add space inside `{...}`... so `{ from: buyer }`

2018-01-30 23:52 UTC, ngan commented on test/disputeTransaction.js
> +
Remove empty line here.

2018-01-31 06:27 UTC, tubaxenor commented
@ngan this is good to review

2018-01-31 18:30 UTC, merged